language: python
python:
  - "2.7"
  - "3.2"
env:
    - QT_API=pyqt4
    - PEP8=1
    - COV=1
matrix:
    allow_failures:
        - env: COV=1
        - env: PEP8=1
    exclude:
        - python: "2.7"
          env: COV=1
        - python: "2.7"
          env: PEP8=1
virtualenv:
    system_site_packages: true
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - sudo apt-get install -qq python-qt4 --fix-missing
    - sudo apt-get install -qq python3-pyqt4 --fix-missing
    - pip install git+https://github.com/pyQode/pyqode.qt.git@dev
script:
    - pip install .
    - if [ $QT_API ]; then
          python runtests.py;
      fi
    - if [ $PEP8 ]; then
          pip install pytest-pep8;
          python runtests.py --pep8 -m pep8;
      fi
    - if [ $COV ]; then
          pip install pytest-cov;
          python runtests.py --cov pyqode;
      fi
after_script:
    - if [ $COV ]; then
        sudo pip install --quiet coveralls;
        coveralls;
      fi
