language: python
python:
 - "2.7"
 - "3.4"
env:
  - QT_API=pyqt4
  - QT_API=pyqt5
  - QT_API=pyqt4 COV=1
  - QT_API=pyqt4 PEP8=1
matrix:
  allow_failures:
      - env: QT_API=pyqt4 COV=1
      - env: QT_API=pyqt4 PEP8=1
  exclude:
      - python: "2.7"
        env: QT_API=pyqt4 COV=1
      - python: "2.7"
        env: QT_API=pyqt4 PEP8=1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.7/sip-4.16.7.tar.gz
  - curl -L -o /downloads/pyqt4.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz
  - curl -L -o /downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4.1/PyQt-gpl-5.4.1.tar.gz
  # Builds
  - if [ ! -d "/builds" ]; then
        sudo mkdir -p /builds;
        sudo chmod a+rw /builds;
    fi
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  - git clone https://github.com/pyQode/pyqode.qt.git
  - pushd pyqode.qt
  - pip install -e .
  - popd
  - pip install -e .
  # Qt4
  - sudo apt-get install -y libqt4-dev
  # Qt5
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-add-repository -y ppa:beineri/opt-qt541;
  - sudo apt-get -qq update;
  - sudo apt-get -qq install g++-4.9 libc6-i386 qt54tools qt54svg qt54webkit;
  - export CXX="g++-4.9";
  - export CC="gcc-4.9";
  # Builds
  - pushd /builds
  # SIP
  - if [ ! -d "sip-4.16.7" ]; then
        tar xzf /downloads/sip.tar.gz --keep-newer-files;
        pushd sip-4.16.7;
        python configure.py;
        make;
        popd;
    fi
  - pushd sip-4.16.7
  - sudo make install
  - popd
  # PyQt4
  # if not cached and needed, build pyqt4 from source
  - if [ "$QT_API" = "pyqt4" ] && [ ! -d "PyQt-x11-gpl-4.11.3" ]; then
        tar xzf /downloads/pyqt4.tar.gz --keep-newer-files;
        pushd PyQt-x11-gpl-4.11.3;
        python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtNetwork -e QtTest;
        make;
        popd;
    fi
  # install pyqt4 if needed
  - if [ "$QT_API" = "pyqt4" ]; then
        pushd PyQt-x11-gpl-4.11.3;
        sudo make install;
        popd;
    fi
  # if not cached and needed, build pyqt5 from source
  - source /opt/qt54/bin/qt54-env.sh
  - if [ "$QT_API" = "pyqt5" ] && [ ! -d "PyQt-gpl-5.4.1" ]; then
        tar xzf /downloads/pyqt5.tar.gz --keep-newer-files;
        pushd PyQt-gpl-5.4.1;
        python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets -e QtNetwork -e QtTest;
        make;
        popd;
    fi
  # install pyqt5 if needed
  - if [ "$QT_API" = "pyqt5" ]; then
        pushd PyQt-gpl-5.4.1;
        sudo make install;
        popd;
    fi
  # Builds Complete
  - popd
script:
  - if [ $COV  ]; then
        py.test --cov pyqode test/;
    elif [ $PEP8 ]; then
        py.test --pep8 -m pep8;
    else
        py.test;
    fi
after_script:
  - if [ $COV ]; then
        pip install --quiet coveralls;
        coveralls;
    fi
cache:
  directories:
    - /builds
  apt: true
