language: python
python:
 - "2.7"
 - "3.2"
env:
  # we only test interpreters who have native python packages
  # since those tests are running on ubuntu 12.04, pyqt5 cannot be tested
  - TOXENV=py27-pyqt4
  - TOXENV=py32-pyqt4
  - TOXENV=cov
  - TOXENV=pep8
matrix:
    exclude:
        - python: "3.2"
          env: TOXENV=cov
        - python: "2.7"
          env: TOXENV=pep8
        - python: "2.7"
          env: TOXENV=py32-pyqt4
        - python: "3.2"
          env: TOXENV=py27-pyqt4
    allow_failures:
        - env: TOXENV=cov
        - env: TOXENV=pep8
virtualenv:
  system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install -qq python-qt4 --fix-missing
  - sudo apt-get install -qq python3-pyqt4 --fix-missing
  - pip install tox
  - pip install pytest-cov
script:
  - if [ $TOXENV == "cov" ]; then
       py.test --cov pyqode --cov-report term;
    else
       tox;
    fi
after_script:
  - if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
    fi
