language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

matrix:
  exclude:
    - env: QT_API=pyqt5
      python: "2.7"

env:
 - QT_API=pyqt4
 - QT_API=pyqt5

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
 - sudo apt-get update

 # Qt
 - python scripts/install-qt.py

 # pytest
 - pip install --quiet pytest pytest-xdist pytest-cov

 # coveralls
 - pip install --quiet coveralls --use-wheel

 # install pyqode.qt from master branch (pyqode.core thighly tied to pyqode.qt)
 - pip install --quiet git+https://github.com/pyQode/pyqode.qt

script:
 - pip install -e .
 - catchsegv py.test --boxed --cov pyqode

after_success:
 - coveralls
